[project]
name = "investment"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.0",
    "numpy>=1.24",
    "scipy>=1.10",
    "matplotlib>=3.7",
    "yfinance>=0.2.0",
    "plotly>=5.0.0",
    "dash>=2.14.0",
    "pyyaml>=6.0",
    "dash-bootstrap-components>=1.5.0",
]
